import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pradhumn Gautam",
  description: "Generated by create next app",
  icons: [
    {
      url: "/photo.jpeg",
      href: "/photo.jpeg",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-zinc-900", roboto.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />

          <div className="pt-24 md:max-w-screen-xl md:mx-auto p-6">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
